# Generated by Django 4.1.9 on 2023-12-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=100)),
                ('courseduration', models.CharField(max_length=100)),
                ('coursedescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feetype', models.CharField(max_length=100)),
                ('totalfee', models.IntegerField()),
                ('feedescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='profile_photos')),
                ('age', models.PositiveIntegerField()),
                ('mobile_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enumber', models.IntegerField()),
                ('fullname', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(default=None, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField()),
                ('adhaarnumber', models.IntegerField()),
                ('fname', models.CharField(default=None, max_length=100)),
                ('mname', models.CharField(default=None, max_length=100)),
                ('address', models.TextField()),
                ('highmarks', models.FloatField()),
                ('intermarks', models.FloatField()),
                ('graduationmarks', models.FloatField()),
                ('profileimage', models.ImageField(blank=True, upload_to='Profiles')),
                ('adhaarpdf', models.FileField(blank=True, upload_to='PDF')),
                ('highschoolpdf', models.FileField(blank=True, upload_to='PDF')),
                ('interpdf', models.FileField(blank=True, upload_to='PDF')),
                ('graduationpdf', models.FileField(blank=True, upload_to='PDF')),
            ],
        ),
    ]
