# Generated by Django 4.1.9 on 2023-06-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enumber', models.IntegerField(max_length=9999999999)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField(max_length=10)),
                ('adhaarnumber', models.IntegerField(max_length=100)),
                ('address', models.TextField()),
                ('highmarks', models.IntegerField(max_length=100)),
                ('intermarks', models.IntegerField(max_length=100)),
                ('graduationmarks', models.IntegerField(max_length=100)),
                ('profileimage', models.ImageField(blank=True, upload_to='Upload/Profiles')),
                ('adhaarpdf', models.FileField(blank=True, upload_to='Upload/PDF')),
                ('highschoolpdf', models.FileField(blank=True, upload_to='Upload/PDF')),
                ('interpdf', models.FileField(blank=True, upload_to='Upload/PDF')),
                ('graduationpdf', models.FileField(blank=True, upload_to='Upload/PDF')),
            ],
        ),
    ]
