# Generated by Django 4.1.9 on 2023-12-02 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentadmission',
            old_name='fname',
            new_name='fathername',
        ),
        migrations.RenameField(
            model_name='studentadmission',
            old_name='mname',
            new_name='mothername',
        ),
    ]
