# Generated by Django 4.1.9 on 2023-06-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentadmission',
            name='gender',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='adhaarnumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='enumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='graduationmarks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='highmarks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='intermarks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
