# Generated by Django 4.1.9 on 2023-12-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_fname_studentadmission_fathername_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmission',
            name='fathername',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='mothername',
            field=models.CharField(max_length=100),
        ),
    ]
