# Generated by Django 4.1.9 on 2023-10-22 10:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_studentadmission_graduationmarks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='totalfee',
        ),
        migrations.RemoveField(
            model_name='studentadmission',
            name='id',
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='fee',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fee',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='authentication.course'),
        ),
        migrations.AddField(
            model_name='fee',
            name='payment_date',
            field=models.DateField(default=datetime.date(2023, 10, 31)),
        ),
        migrations.AddField(
            model_name='studentadmission',
            name='fee',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='authentication.fee'),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.course'),
        ),
        migrations.AlterField(
            model_name='studentadmission',
            name='enumber',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
