# Generated by Django 4.1.9 on 2023-06-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feetype', models.CharField(max_length=100)),
                ('totalfee', models.IntegerField()),
                ('feedescription', models.TextField()),
            ],
        ),
    ]
