# Generated by Django 4.1.9 on 2023-06-12 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='profile_photos')),
                ('age', models.PositiveIntegerField()),
                ('mobile_number', models.CharField(max_length=20)),
            ],
        ),
    ]
