# Generated by Django 4.1.9 on 2023-11-12 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_course_course_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentAdmission',
            new_name='EnrolledStudent',
        ),
    ]
