# Generated by Django 4.1.9 on 2023-12-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_delete_fee_course_totalfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='feepayment',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
