# Generated by Django 4.1.9 on 2023-11-12 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_studentadmission_enrolledstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.course'),
        ),
    ]
